# Generated by Django 6.0.5 on 2026-05-22 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('FileId', models.AutoField(primary_key=True, serialize=False)),
                ('FileName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Personengruppe',
            fields=[
                ('Personengruppe_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Personengruppe_Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('Status_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Status_Bedeutung', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Veranstalter',
            fields=[
                ('Veranstalter_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Veranstalter_Name', models.CharField(max_length=150)),
                ('Veranstalter_Email', models.EmailField(max_length=254, null=True)),
                ('Veranstalter_Telefonnummer', models.CharField(max_length=100, null=True)),
                ('Veranstalter_Hauptsitz', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veranstaltung_Kategorie',
            fields=[
                ('Veranstaltung_Kategorie_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Kategorie_Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Person_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Vorname', models.CharField(max_length=150)),
                ('Nachname', models.CharField(max_length=150)),
                ('Person_Email', models.EmailField(max_length=254)),
                ('Person_HashedPassword', models.CharField(max_length=150)),
                ('Person_Salt', models.CharField(max_length=150)),
                ('Personengruppe_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.personengruppe')),
            ],
        ),
        migrations.CreateModel(
            name='Veranstaltung',
            fields=[
                ('Veranstaltung_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Veranstaltung_Beschreibung', models.TextField()),
                ('Veranstaltung_Webseite', models.CharField(max_length=100)),
                ('Veranstaltung_Sprache', models.CharField(max_length=50)),
                ('Veranstaltung_Subevent', models.CharField(max_length=50)),
                ('Veranstaltung_Name', models.CharField(max_length=150)),
                ('Veranstalter_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.veranstalter')),
                ('Veranstaltung_Kategorie_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.veranstaltung_kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Veranstaltung_Einladung',
            fields=[
                ('Veranstaltung_Einladung_ID', models.AutoField(primary_key=True, serialize=False)),
                ('VIP_anwesend', models.BooleanField()),
                ('Ticket_Typ', models.CharField(max_length=150)),
                ('Veranstaltung_Grund', models.TextField()),
                ('Anzahl_Eingeladener_Gäste', models.IntegerField()),
                ('Einladung_Datum', models.DateTimeField(auto_now_add=True)),
                ('Anfragesteller_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.person')),
                ('Repraesentiert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.personengruppe')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.status')),
                ('Veranstaltung_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.veranstaltung')),
            ],
        ),
        migrations.CreateModel(
            name='Einladung_Kommentar',
            fields=[
                ('Kommentar_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Kommentar_Inhalt', models.TextField()),
                ('Verfassungsdatum', models.DateTimeField(auto_now_add=True)),
                ('Parent_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.einladung_kommentar')),
                ('Absender_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.person')),
                ('Veranstaltung_Einladung_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.veranstaltung_einladung')),
            ],
        ),
        migrations.CreateModel(
            name='Einladung_Entscheidung',
            fields=[
                ('pk', models.CompositePrimaryKey('Veranstaltung_Einladung_ID', 'Personengruppe_ID', blank=True, editable=False, primary_key=True, serialize=False)),
                ('Zugesagt', models.BooleanField()),
                ('Anmerkung', models.TextField()),
                ('Entscheidungs_Datum', models.DateTimeField(auto_now_add=True)),
                ('Zugesagt_von_Person_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.person')),
                ('Personengruppe_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.personengruppe')),
                ('Veranstaltung_Einladung_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.veranstaltung_einladung')),
            ],
        ),
        migrations.CreateModel(
            name='Veranstaltung_Ticket_Umfang',
            fields=[
                ('Ticket_Typ', models.CharField(max_length=150)),
                ('pk', models.CompositePrimaryKey('Veranstaltung_ID', 'Ticket_Typ', blank=True, editable=False, primary_key=True, serialize=False)),
                ('Aufnahmen', models.BooleanField()),
                ('Aufnahmen_Zensiert', models.BooleanField()),
                ('Umfang_der_Aufnahmen', models.TextField()),
                ('Kosten', models.FloatField()),
                ('Veranstaltung_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.veranstaltung')),
            ],
        ),
        migrations.AddField(
            model_name='veranstaltung_einladung',
            name='Veranstaltung_Ticket_Umfang_pk',
            field=models.ForeignObject(from_fields=('Veranstaltung_ID', 'Ticket_Typ'), on_delete=django.db.models.deletion.CASCADE, to='webserver.veranstaltung_ticket_umfang', to_fields=('Veranstaltung_ID', 'Ticket_Typ')),
        ),
        migrations.AddConstraint(
            model_name='veranstaltung',
            constraint=models.UniqueConstraint(fields=('Veranstaltung_Name', 'Veranstaltung_Subevent'), name='Veranstaltung und Subevent'),
        ),
    ]
